-- Add ai_analysis JSONB column to scans table for caching AI-generated security analysis
ALTER TABLE scans ADD COLUMN IF NOT EXISTS ai_analysis JSONB DEFAULT NULL;

-- Add comment for documentation
COMMENT ON COLUMN scans.ai_analysis IS 'Cached AI security analysis generated by Claude. Contains executiveSummary, riskLevel, attackChains, topPriorities, positives.';
